Add files via upload
Plugin could not be activated because it triggered a fatal error.

Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in C:\xampp\htdocs\AlphaCreatives\wp-content\plugins\trx_addons\components\widgets\widgets.php on line 316